name = "supreme-admin-worker"
main = "worker-prime-fetcher.js"
compatibility_date = "2025-02-04"
workers_dev = true

[triggers]
crons = [
  "0 */12 * * *"
]

[[kv_namespaces]]
binding = "STATE"
id = "a27b4f2d29124505a560ef727a1f4d36"

[vars]
START_PAGE = ""
REFRESH_START_ID=""
